In [28]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

In [29]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [30]:
print(df.isnull().sum())

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [32]:
df.describe(include = 'all')# for including categorical data in the summary statistics

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [35]:
df['Review Rating'] = df['Review Rating'].fillna(df.groupby('Category')['Review Rating'].transform('median'))
# instead of filling the missing values with the overall median, we fill them with the median of the respective category. This way, we preserve the inherent differences between categories and provide a more accurate representation of the data.

In [34]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [54]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')# to make the column names more consistent and easier to work with. This is a common practice in data analysis to ensure that column names are standardized and do not contain spaces, which can cause issues when referencing them in code.

In [55]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [56]:
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [58]:
# creating a column with categories of ages
labels = ['Young Adult', 'Adult', 'Middle-Aged','Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels)

In [61]:
df[['age', 'age_group']].head()

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged

In [62]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [63]:
df[['frequency_of_purchases', 'purchase_frequency_days']].head()

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365

In [64]:
df['purchase_frequency_days'].isnull().sum()

np.int64(0)

In [72]:
df[['discount_applied', 'promo_code_used']].head()
# is there any column where discount_applied is true but promo_code_used is false? This would indicate that a discount was applied without using a promo code, which could be an interesting insight into the shopping behavior of customers.
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [73]:
df = df.drop(columns = ['promo_code_used'] )

In [74]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [76]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\anwes\appdata\local\programs\python\python313\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\anwes\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anwes\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 407.2 kB/s eta 0:00:06
   ------- -------------------------------- 0.5/2.8 MB 407.2 kB/s eta 0:00:06
   ------- -------------------------------- 0.5/2.8 MB 407.2 kB/s eta 0:00:06
   ------- -------------------------------- 0.5/2.8 MB 407.2 kB/s eta 0:00:06
   ------- -------------------------------- 0.5/2.8 MB 407.2 kB/s eta 0:00:06
   ----------- ---------------------------- 0.8/2.8 MB 296.8 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 296.8 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 296.8 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 296.8 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 296.8 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.8 MB 286.0 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 286.0 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 333.8 kB/s eta 0:00:05
   ------------------- -------------------- 1.3/2.8 MB 333.8 kB/s eta 0:00:05
   ------------------- -------------------- 1.3/2.8 MB 333.8 kB/s eta 0:00:05
   ---------------------- ----------------- 1.6/2.8 MB 339.7 kB/s eta 0:00:04
   ---------------------- ----------------- 1.6/2.8 MB 339.7 kB/s eta 0:00:04
   ---------------------- ----------------- 1.6/2.8 MB 339.7 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 359.0 kB/s eta 0:00:03
   -------------------------- ------------- 1.8/2.8 MB 359.0 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 375.5 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 375.5 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 375.5 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 388.2 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 388.2 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 388.2 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.8 MB 391.7 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 399.0 kB/s  0:00:06
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [79]:
# connect to postgresql database and load the data into a table named 'customer_behavior'
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:Anwesh@localhost:5432/customer_behaviour')
df.to_sql('customer_behavior', engine, if_exists='replace', index=False)

900